/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './src/app/**/*.{js,ts,jsx,tsx,mdx}',
        './src/components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/**/*.{html,js,ts,jsx,tsx,mdx}',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                // Background
                'background': 'hsl(var(--color-background))',
                'background-primary': 'hsl(var(--color-background-primary))',
                'background-secondary': 'hsl(var(--color-background-secondary))',
                'background-body': 'hsl(var(--color-background-body))',
                'background-card': 'hsl(var(--color-background-card))',
                'background-popover': 'hsl(var(--color-background-popover))',
                'background-small': 'hsl(var(--color-background-small))',
                'background-hover': 'hsl(var(--color-background-hover))',
                'background-hover-secondary': 'hsl(var(--color-background-hover-secondary))',
                'background-card-hover': 'hsl(var(--color-background-card-hover))',
                'background-popover-hover': 'hsl(var(--color-background-popover-hover))',
                'background-destructive': 'hsl(var(--color-background-destructive))',
                'background-success': 'hsl(var(--color-background-success))',

                // Brand
                'brand': 'hsl(var(--color-brand))',
                'brand-hover': 'hsl(var(--color-brand-hover))',

                // Text
                'text-primary': 'hsl(var(--color-text-primary))',
                'text-secondary': 'hsl(var(--color-text-secondary))',
                'text-tertiary': 'hsl(var(--color-text-tertiary))',
                'text-icon': 'hsl(var(--color-text-icon))',
                'text-destructive': 'hsl(var(--color-text-destructive))',
                'text-brand-foreground': 'hsl(var(--color-text-brand-foreground))',
                'text-helper': 'hsl(var(--color-text-helper))',
                'text-brand': 'hsl(var(--color-text-brand))',
                'text-placeholder': 'hsl(var(--color-text-placeholder))',

                // Border
                'border': 'hsl(var(--color-border))',
                'border-card': 'hsl(var(--color-border-card))',
                'border-brand': 'hsl(var(--color-border-brand))',

                // Ring / Caret
                'ring-primary': 'hsl(var(--color-ring-primary))',
                'ring-brand': 'hsl(var(--color-ring-brand))',
                'caret-brand': 'hsl(var(--color-caret-brand))',

                // Black shades
                'black-50': 'hsl(var(--black-50))',
                'black-100': 'hsl(var(--black-100))',
                'black-200': 'hsl(var(--black-200))',
                'black-300': 'hsl(var(--black-300))',
                'black-400': 'hsl(var(--black-400))',
                'black-500': 'hsl(var(--black-500))',
                'black-600': 'hsl(var(--black-600))',
                'black-700': 'hsl(var(--black-700))',
                'black-800': 'hsl(var(--black-800))',
                'black-900': 'hsl(var(--black-900))',
                'black-950': 'hsl(var(--black-950))',
                'black-975': 'hsl(var(--black-975))',

                // White shades
                'white-50': 'hsl(var(--white-50))',
                'white-100': 'hsl(var(--white-100))',
                'white-200': 'hsl(var(--white-200))',
                'white-300': 'hsl(var(--white-300))',
                'white-400': 'hsl(var(--white-400))',
                'white-500': 'hsl(var(--white-500))',
                'white-600': 'hsl(var(--white-600))',
                'white-700': 'hsl(var(--white-700))',
                'white-800': 'hsl(var(--white-800))',
                'white-900': 'hsl(var(--white-900))',
                'white-950': 'hsl(var(--white-950))',
                'white-975': 'hsl(var(--white-975))',
                'white-1000': 'hsl(var(--white-1000))',

                // Red shades
                'red-50': 'hsl(var(--red-50))',
                'red-100': 'hsl(var(--red-100))',
                'red-200': 'hsl(var(--red-200))',
                'red-300': 'hsl(var(--red-300))',
                'red-400': 'hsl(var(--red-400))',
                'red-500': 'hsl(var(--red-500))',
                'red-600': 'hsl(var(--red-600))',
                'red-700': 'hsl(var(--red-700))',
                'red-800': 'hsl(var(--red-800))',
                'red-900': 'hsl(var(--red-900))',
                'red-950': 'hsl(var(--red-950))',
                'red-975': 'hsl(var(--red-975))',
                'red-1000': 'hsl(var(--red-1000))',

                // Orange shades
                'orange-50': 'hsl(var(--orange-50))',
                'orange-100': 'hsl(var(--orange-100))',
                'orange-200': 'hsl(var(--orange-200))',
                'orange-300': 'hsl(var(--orange-300))',
                'orange-400': 'hsl(var(--orange-400))',
                'orange-500': 'hsl(var(--orange-500))',
                'orange-600': 'hsl(var(--orange-600))',
                'orange-700': 'hsl(var(--orange-700))',
                'orange-800': 'hsl(var(--orange-800))',
                'orange-900': 'hsl(var(--orange-900))',
                'orange-950': 'hsl(var(--orange-950))',
                'orange-975': 'hsl(var(--orange-975))',

                // Green, Teal, Blue, Purple, Cyan, Magenta, Yellow (repeat same pattern)
                'green-50': 'hsl(var(--green-50))',
                'green-100': 'hsl(var(--green-100))',
                'green-200': 'hsl(var(--green-200))',
                'green-300': 'hsl(var(--green-300))',
                'green-400': 'hsl(var(--green-400))',
                'green-500': 'hsl(var(--green-500))',
                'green-600': 'hsl(var(--green-600))',
                'green-700': 'hsl(var(--green-700))',
                'green-800': 'hsl(var(--green-800))',
                'green-900': 'hsl(var(--green-900))',
                'green-950': 'hsl(var(--green-950))',
                'green-975': 'hsl(var(--green-975))',
                'green-1000': 'hsl(var(--green-1000))',

                'teal-50': 'hsl(var(--teal-50))',
                'teal-100': 'hsl(var(--teal-100))',
                'teal-200': 'hsl(var(--teal-200))',
                'teal-300': 'hsl(var(--teal-300))',
                'teal-400': 'hsl(var(--teal-400))',
                'teal-500': 'hsl(var(--teal-500))',
                'teal-600': 'hsl(var(--teal-600))',
                'teal-700': 'hsl(var(--teal-700))',
                'teal-800': 'hsl(var(--teal-800))',
                'teal-900': 'hsl(var(--teal-900))',
                'teal-950': 'hsl(var(--teal-950))',
                'teal-975': 'hsl(var(--teal-975))',
                'teal-1000': 'hsl(var(--teal-1000))',

                'blue-50': 'hsl(var(--blue-50))',
                'blue-100': 'hsl(var(--blue-100))',
                'blue-200': 'hsl(var(--blue-200))',
                'blue-300': 'hsl(var(--blue-300))',
                'blue-400': 'hsl(var(--blue-400))',
                'blue-500': 'hsl(var(--blue-500))',
                'blue-600': 'hsl(var(--blue-600))',
                'blue-700': 'hsl(var(--blue-700))',
                'blue-800': 'hsl(var(--blue-800))',
                'blue-900': 'hsl(var(--blue-900))',
                'blue-950': 'hsl(var(--blue-950))',
                'blue-975': 'hsl(var(--blue-975))',
                'blue-1000': 'hsl(var(--blue-1000))',

                'purple-50': 'hsl(var(--purple-50))',
                'purple-100': 'hsl(var(--purple-100))',
                'purple-200': 'hsl(var(--purple-200))',
                'purple-300': 'hsl(var(--purple-300))',
                'purple-400': 'hsl(var(--purple-400))',
                'purple-500': 'hsl(var(--purple-500))',
                'purple-600': 'hsl(var(--purple-600))',
                'purple-700': 'hsl(var(--purple-700))',
                'purple-800': 'hsl(var(--purple-800))',
                'purple-900': 'hsl(var(--purple-900))',
                'purple-950': 'hsl(var(--purple-950))',
                'purple-975': 'hsl(var(--purple-975))',
                'purple-1000': 'hsl(var(--purple-1000))',

                'magenta-50': 'hsl(var(--magenta-50))',
                'magenta-100': 'hsl(var(--magenta-100))',
                'magenta-200': 'hsl(var(--magenta-200))',
                'magenta-300': 'hsl(var(--magenta-300))',
                'magenta-400': 'hsl(var(--magenta-400))',
                'magenta-500': 'hsl(var(--magenta-500))',
                'magenta-600': 'hsl(var(--magenta-600))',
                'magenta-700': 'hsl(var(--magenta-700))',
                'magenta-800': 'hsl(var(--magenta-800))',
                'magenta-900': 'hsl(var(--magenta-900))',
                'magenta-950': 'hsl(var(--magenta-950))',
                'magenta-975': 'hsl(var(--magenta-975))',
                'magenta-1000': 'hsl(var(--magenta-1000))',

                'yellow-50': 'hsl(var(--yellow-50))',
                'yellow-100': 'hsl(var(--yellow-100))',
                'yellow-200': 'hsl(var(--yellow-200))',
                'yellow-300': 'hsl(var(--yellow-300))',
                'yellow-400': 'hsl(var(--yellow-400))',
                'yellow-500': 'hsl(var(--yellow-500))',
                'yellow-600': 'hsl(var(--yellow-600))',
                'yellow-700': 'hsl(var(--yellow-700))',
                'yellow-800': 'hsl(var(--yellow-800))',
                'yellow-900': 'hsl(var(--yellow-900))',
                'yellow-950': 'hsl(var(--yellow-950))',
                'yellow-975': 'hsl(var(--yellow-975))',
                'yellow-1000': 'hsl(var(--yellow-1000))',
            },
            borderRadius: {
                lg2: 'var(--radius-lg2)',
            },
            fontFamily: {
                body: 'var(--font-body)',
            },
            animation: {
                loading: 'spin 850ms linear infinite',
            },
        },
    },
    plugins: [
        require('tailwindcss-animate')],
}
