import ClientLayout from './ClientLayout';
import './globals.css';
import { TRPCProvider } from './providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TRPCProvider>
          <ClientLayout>{children}</ClientLayout>
        </TRPCProvider>
      </body>
    </html>
  );
}
